### ISSUE TITLE
How to install properly

### ISSUE THREAD

**Issue by hackguy25** [tibicen/meshroom2blender#3]
I have absolutely no experience with custom Blender plugins.
When I tried to install the plugin as a zip file (of the whole repository) and as the `__init__.py` script both approaches failed.
In the end what worked was renaming `init.py` to `import_meshroom.py` and installing that.
Is there a *proper* way of installing the plugin?

**Comment by tibicen** [comment]
- If there is `__init__.py` file, then the addon is standard python "module", and should be in a folder named as an addon.
- otherwise it can be renamed to regular addon name, and be just a simple file addon. 

I should check how it works after installing from downloaded file... 

[Edit] When I downloaded the repo and installed as a zip file it worked properly.
![obraz](https://user-images.githubusercontent.com/5797670/60610730-c5d91580-9dc4-11e9-852f-ed3ea2375030.png)

**Comment by tibicen** [comment]
did it works with this kind of download, can I close it?

**Comment by hackguy25** [comment]
Sorry, I totally forgot about this. Will try tomorrow.

**Comment by hackguy25** [comment]
So I tried it, works for `master` branch, does not work for `0.1.0` branch.

**Comment by tibicen** [comment]
ach ok. My workflow is that master is official, and versions are under developement branches.
Soon I will update it. :)
